package ita.micc.meteorcity.database.interfaces;

import ita.micc.meteorcity.database.query.QueryInfo;

import java.sql.SQLException;
import java.util.List;

/** Query interface
 * @author Codeh
 */
public interface QueryInterface {

    /**
     * Fetch specific class data from database.
     * @param returnData Class that will be bound.
     * @param queryInfo Query
     * @return null if no data was found.
     */
    <A> List<A> fetchClassData(Class<A> returnData, QueryInfo queryInfo);


    /**
     * Insert bind object into database.
     * @param int which will be returned.
     * @param query which will be executed.
     * @return object generated by database (Integer, varchar..)
     */
    int insertObjectDataInt(QueryInfo queryInfo);

    /**
     * Execute single or multiple query.
     * @param queryExecutes all queries or single.
     * @return true if committed, if false rollback.
     */
    boolean executeQuery(QueryInfo... queryInfo);

    /**
     * Check if specific row exist.
     * @param queryInfo query
     * @return true if row exist.
     */
    boolean existRow(String query) throws SQLException;
}
