name: MeteorCity
version: '${project.version}'
main: ita.micc.meteorcity.MeteorCity
api-version: 1.18
depend:
  - WorldEdit
  - DeluxeMenus
  - PlaceholderAPI
authors: [ Codeh ]
description: Plugin for create City
commands:
  city:
    description: city command for city utility.
  cityadmin:
    description: city command for admin.
